export enum NAVIGATION_ACTIONS {
  RESET = 'RESET',
  GO_BACK = 'GO_BACK',
  NAVIGATE = 'NAVIGATE',
  DISPATCH = 'DISPATCH',
  STACK_RESET = 'STACK_RESET',
  STACK_POP = 'STACK_POP',
  STACK_PUSH = 'STACK_PUSH',
  STACK_REPLACE = 'STACK_REPLACE',
}
