export enum ROUTES_STACKS {
  PUBLIC = 'STACK_PUBLIC',
  PRIVATE = 'STACK_PRIVATE',
}

export enum ROUTES {
  // PUBLIC ROUTES
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  // PRIVATE ROUTES
  HOME_TAB = 'HOME_TAB',
  TRADE_TAB = 'TRADE_TAB',
  PORTIFOLIO_TAB = 'PORTIFOLIO_TAB',
  // HOME ROUTES
  HOME = 'HOME',
  FUND_DETAILS = 'FUND_DETAILS',
}

export enum MODALS {
  DEFAULT = 'DEFAULT',
}
